import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, Check } from "lucide-react";
import contractor from "../assets/portfolio-contractor-clean.jpg?w=1400&format=webp&quality=76";
import contractorSet from "../assets/portfolio-contractor-clean.jpg?w=640;960;1200;1400&format=webp&quality=76&as=srcset";
import restaurant from "../assets/portfolio-restaurant-clean.jpg?w=1400&format=webp&quality=76";
import restaurantSet from "../assets/portfolio-restaurant-clean.jpg?w=640;960;1200;1400&format=webp&quality=76&as=srcset";
import { PHONE, PHONE_TEL } from "../components/site-layout";

export const Route=createFileRoute("/")({head:()=>({meta:[
{title:"CoreLinkDev: Premium Small Business Websites, $499 Flat"},
{name:"description",content:"Premium small business websites built for speed, trust, and conversion. See a working demo before you pay. $499 flat build, optional $39 monthly care."},
{property:"og:title",content:"CoreLinkDev: Premium Small Business Websites"},
{property:"og:description",content:"Premium small business websites. Working demo before payment. $499 flat build."},
{property:"og:url",content:"https://corelinkdev.com/"},
{property:"og:image",content:"https://corelinkdev.com/og-cover.jpg"}],links:[{rel:"canonical",href:"https://corelinkdev.com/"}]}),component:HomePage});

function HomePage(){return <><Hero/><Work/><Studio/><Process/><Pricing/><FinalCta/></>}

function Hero(){return <section className="bg-background"><div className="container-wide py-10 md:py-16">
<div className="border-t border-hairline pt-5"><div className="grid gap-8 lg:grid-cols-12">
<p className="eyebrow lg:col-span-3">Independent web studio</p>
<div className="lg:col-span-9"><h1 className="max-w-[13ch] text-[3.25rem] font-medium leading-[.92] tracking-[-.06em] text-ink sm:text-[4.5rem] md:text-[6.5rem] lg:text-[8rem]">Websites built to make a small business feel established.</h1>
<div className="mt-8 grid gap-7 border-t border-hairline pt-6 md:grid-cols-2"><p className="max-w-xl text-base leading-7 text-ink-soft md:text-lg">Strategy, design and development handled as one job. You see a working version before you decide to pay for it.</p>
<div className="flex flex-wrap items-start gap-x-6 gap-y-3 md:justify-end"><Link to="/contact" className="text-sm font-semibold text-ink underline decoration-1 underline-offset-4">Request a free demo ↗</Link><Link to="/portfolio" className="text-sm font-semibold text-ink underline decoration-1 underline-offset-4">View work</Link><a href={`tel:${PHONE_TEL}`} className="text-sm text-ink-soft">{PHONE}</a></div></div></div></div></div>
<div className="mt-10 grid gap-6 border-y border-hairline py-7 md:grid-cols-3"><div><p className="text-xs uppercase tracking-[.14em] text-ink-mute">Design</p><p className="mt-2 text-lg font-medium text-ink">Custom to the business</p></div><div><p className="text-xs uppercase tracking-[.14em] text-ink-mute">Build</p><p className="mt-2 text-lg font-medium text-ink">Responsive and fast</p></div><div><p className="text-xs uppercase tracking-[.14em] text-ink-mute">Launch</p><p className="mt-2 text-lg font-medium text-ink">Demo before payment</p></div></div>
<div className="grid grid-cols-3 border-b border-hairline py-5 text-sm"><div><strong className="block text-ink">$499</strong><span className="text-ink-mute">website build</span></div><div><strong className="block text-ink">Demo first</strong><span className="text-ink-mute">before payment</span></div><div><strong className="block text-ink">Yours</strong><span className="text-ink-mute">full ownership</span></div></div>
</div></section>}

function Work(){const projects=[{name:"Trattoria Milano",type:"Restaurant",src:restaurant,set:restaurantSet},{name:"Craftwood Builders",type:"Contractor",src:contractor,set:contractorSet}];return <section id="work" className="py-16 md:py-24"><div className="container-wide">
<div className="grid gap-8 border-t border-hairline pt-5 lg:grid-cols-12"><p className="eyebrow lg:col-span-3">Selected work</p><div className="lg:col-span-9"><h2 className="max-w-[14ch] text-4xl font-medium leading-[.98] tracking-[-.05em] text-ink md:text-6xl">Different businesses. Different jobs for the website.</h2></div></div>
<div className="mt-12 grid gap-x-6 gap-y-12 md:grid-cols-2">{projects.map((p,i)=><article key={p.name} className=""><figure className="overflow-hidden bg-surface"><img src={p.src} srcSet={p.set} sizes="(min-width:768px) 50vw,100vw" alt={`${p.type} website concept by CoreLinkDev.`} width={1400} height={875} loading="lazy" className="w-full"/></figure><div className="mt-4 flex items-start justify-between border-t border-hairline pt-3"><div><p className="text-lg font-semibold text-ink">{p.name}</p><p className="mt-1 text-sm text-ink-mute">{p.type} · Concept project</p></div><ArrowUpRight className="h-5 w-5 text-ink"/></div></article>)}</div>
<div className="mt-12 text-right"><Link to="/portfolio" className="text-sm font-semibold underline underline-offset-4">All work ↗</Link></div>
</div></section>}

function Studio(){const rows=[["Positioning","What should a visitor understand in the first ten seconds?"],["Design","A visual system that belongs to your business, not a generic template."],["Development","Responsive, accessible pages built for speed and clarity."],["Launch & care","Forms, domain setup, hosting, security, backups and ongoing edits."]];return <section className="border-y border-hairline py-16 md:py-24"><div className="container-wide"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow">What we do</p><h2 className="mt-5 max-w-[9ch] text-4xl font-medium leading-[.98] tracking-[-.05em] md:text-6xl">One studio. One connected job.</h2></div><div className="lg:col-span-8">{rows.map(([t,d])=><div key={t} className="grid gap-3 border-b border-hairline py-6 first:border-t md:grid-cols-[200px_1fr]"><h3 className="text-lg font-semibold text-ink">{t}</h3><p className="max-w-xl text-sm leading-7 text-ink-soft">{d}</p></div>)}</div></div></div></section>}

const STEPS=[["01","Tell us about the business"],["02","See a working direction"],["03","Review and refine"],["04","Approve and launch"]];
function Process(){return <section className="py-16 md:py-24"><div className="container-wide"><div className="grid gap-8 border-t border-hairline pt-5 lg:grid-cols-12"><p className="eyebrow lg:col-span-3">Process</p><div className="lg:col-span-9"><h2 className="max-w-[14ch] text-4xl font-medium leading-[.98] tracking-[-.05em] md:text-6xl">See the work early. Decide with something real in front of you.</h2></div></div><ol className="mt-12 grid border-t border-hairline md:grid-cols-4">{STEPS.map(([n,t])=><li key={n} className="border-b border-hairline py-6 md:border-r md:px-5 md:last:border-r-0"><span className="text-xs text-ink-mute">{n}</span><h3 className="mt-8 max-w-[15ch] text-xl font-medium leading-tight text-ink">{t}</h3></li>)}</ol></div></section>}

const BUILD=["Custom design","Responsive development","Contact forms","Basic SEO setup","Performance tuning","SSL setup","Full ownership","Launch assistance"];
const CARE=["Hosting","Security monitoring","Backups","Software updates","Bug fixes","Content edits","Performance checks","Priority support"];
function Pricing(){return <section id="pricing" className="border-y border-hairline py-16 md:py-24"><div className="container-wide"><div className="grid gap-8 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow">Pricing</p><h2 className="mt-5 text-4xl font-medium leading-[.98] tracking-[-.05em] md:text-6xl">Simple enough to understand in one minute.</h2></div><div className="lg:col-span-8"><div className="grid border-t border-hairline md:grid-cols-2">
<Plan title="Website build" price="$499" suffix="one time" copy="Design, development and launch. You see the working demo before payment." features={BUILD} primary/>
<Plan title="Optional care" price="$39" suffix="/ month" copy="Hosting, security, backups, maintenance, one standard domain registration or renewal, business email hosting, and small content updates." features={CARE}/>
</div></div></div></div></section>}
export function CombinedPlanCard(){return <div className="grid border-t border-hairline md:grid-cols-2"><Plan title="Website build" price="$499" suffix="one time" copy="Design, development and launch. You see the working demo before payment." features={BUILD} primary/><Plan title="Optional care" price="$39" suffix="/ month" copy="Hosting, security, backups, maintenance and small content updates." features={CARE}/></div>}\nfunction Plan({title,price,suffix,copy,features,primary=false}:{title:string;price:string;suffix:string;copy:string;features:string[];primary?:boolean}){return <div className={`border-b border-hairline py-8 md:px-8 ${primary?"md:border-r":""}`}><p className="eyebrow">{title}</p><p className="mt-6 flex items-end gap-2"><span className="text-6xl font-medium tracking-[-.06em] text-ink">{price}</span><span className="pb-2 text-sm text-ink-mute">{suffix}</span></p><p className="mt-5 max-w-sm text-sm leading-7 text-ink-soft">{copy}</p><ul className="mt-7 grid gap-2 text-sm text-ink">{features.map(f=><li key={f} className="flex gap-2"><Check className="mt-0.5 h-4 w-4"/>{f}</li>)}</ul>{primary&&<Link to="/contact" className="mt-8 inline-flex text-sm font-semibold underline underline-offset-4">Request a free demo ↗</Link>}</div>}

function FinalCta(){return <section className="py-16 md:py-24"><div className="container-wide"><div className="grid gap-8 border-t border-hairline pt-5 lg:grid-cols-12"><p className="eyebrow lg:col-span-3">Start a project</p><div className="lg:col-span-9"><h2 className="max-w-[13ch] text-5xl font-medium leading-[.95] tracking-[-.055em] text-ink md:text-7xl">Show us the business. We’ll show you what the website could be.</h2><div className="mt-8 flex flex-wrap gap-6"><Link to="/contact" className="text-sm font-semibold underline underline-offset-4">Request a free demo ↗</Link><a href={`tel:${PHONE_TEL}`} className="text-sm text-ink-soft">Call {PHONE}</a></div></div></div></div></section>}
